TRI_LAYER_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball

WPM_ENABLE = yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

LTO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes

MOUSE_KEY_ENABLE = yes

